version: '3.7'
services:
  database:
    image: postgres:15.3
    container_name: ${COMPOSE_PROJECT_NAME}_database
    restart: unless-stopped
    environment:
      TZ: Asia/Yekaterinburg
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./database/volumes/data:/var/lib/postgresql/data
    networks:
      - default
    logging:
      driver: json-file
      options:
        max-size: 100m

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}_default
    driver: bridge
